/** Design tokens aligned with DESIGN.md (Cohere-inspired system) */

export const BrandColors = {
  black: '#000000',
  nearBlack: '#17171c',
  enterpriseGreen: '#003c33',
  darkNavy: '#071829',
  actionBlue: '#1863dc',
  coral: '#ff7759',
  softCoral: '#ffad9b',
} as const;

export const LightTheme = {
  canvas: '#ffffff',
  canvasSoft: '#eeece7',
  canvasGreenWash: '#edfce9',
  canvasBlueWash: '#f1f5ff',
  surface: '#ffffff',
  surfaceCard: '#eeece7',
  surfaceStrong: '#f2f2f2',
  surfaceDark: BrandColors.enterpriseGreen,
  surfaceNavy: BrandColors.darkNavy,
  border: '#f2f2f2',
  borderHairline: '#d9d9dd',
  borderLight: '#e5e7eb',
  ink: '#212121',
  body: '#212121',
  muted: '#93939f',
  slate: '#75758a',
  primary: BrandColors.nearBlack,
  primaryActive: '#000000',
  accent: BrandColors.coral,
  accentSoft: BrandColors.softCoral,
  link: BrandColors.actionBlue,
  onPrimary: '#ffffff',
  onAccent: BrandColors.nearBlack,
  onDark: '#ffffff',
  success: '#003c33',
  warning: BrandColors.coral,
  error: '#b30000',
  info: BrandColors.actionBlue,
  focus: '#4c6ee6',
  focusInput: '#9b60aa',
  switchTrackOff: '#e5e7eb',
  switchTrackOn: BrandColors.nearBlack,
} as const;

export const DarkTheme = {
  canvas: BrandColors.enterpriseGreen,
  canvasSoft: '#002a24',
  canvasGreenWash: '#003c33',
  canvasBlueWash: BrandColors.darkNavy,
  surface: '#002a24',
  surfaceCard: '#001f1b',
  surfaceStrong: '#003c33',
  surfaceDark: BrandColors.nearBlack,
  surfaceNavy: BrandColors.darkNavy,
  border: '#1a4a42',
  borderHairline: '#2a5a52',
  borderLight: '#1f3d38',
  ink: '#ffffff',
  body: '#e8e8ec',
  muted: '#93939f',
  slate: '#75758a',
  primary: '#ffffff',
  primaryActive: '#f2f2f2',
  accent: BrandColors.coral,
  accentSoft: BrandColors.softCoral,
  link: '#6b9fff',
  onPrimary: BrandColors.nearBlack,
  onAccent: BrandColors.nearBlack,
  onDark: '#ffffff',
  success: '#edfce9',
  warning: BrandColors.coral,
  error: '#ff6b6b',
  info: '#6b9fff',
  focus: '#4c6ee6',
  focusInput: '#9b60aa',
  switchTrackOff: '#2a5a52',
  switchTrackOn: '#ffffff',
} as const;

export type ThemeColors = typeof LightTheme | typeof DarkTheme;

export const Spacing = {
  px: 1,
  half: 2,
  one: 4,
  oneHalf: 6,
  two: 8,
  twoHalf: 10,
  three: 12,
  four: 16,
  five: 20,
  six: 22,
  seven: 24,
  eight: 28,
  nine: 32,
  ten: 36,
  eleven: 40,
  twelve: 56,
  thirteen: 60,
  fourteen: 64,
  fifteen: 80,
} as const;

export const Radius = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 22,
  xl: 30,
  pill: 32,
  full: 9999,
} as const;

export const MaxContentWidth = 800;

export const Animation = {
  fast: 150,
  normal: 250,
  slow: 400,
} as const;
